### PR TITLE
Depend on akka 2.4.0

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by agemooij** [comment]
I think we should indeed switch to 2.4 and remove support for older versions of Akka (and Scala).

**Comment by agemooij** [comment]
We might have to update the README though. Unfortunately I only thought of that after I already merged the PR.

**Comment by raboof** [comment]
The readme doesn't appear to mention any version numbers?

**Comment by agemooij** [comment]
And that's the problem we should solve, right? If Stamina is Akka 2.4.x only, then I think we should mention that somewhere.

**Pull request merged**
